FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH="/app"

RUN apt update &&  \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app/src

COPY ./src/connectors ./connectors
COPY ./src/db_models ./db_models
COPY ./src/settings.py ./
COPY ./migrations ./migrations
COPY ./pyproject.toml ./uv.lock ./alembic.ini ./

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN pip install uv && \
    uv pip install --system -r pyproject.toml
