"""added order table

Revision ID: f9d500569def
Revises: 4e45f0a0551c
Create Date: 2025-12-17 20:09:35.499891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9d500569def'
down_revision: Union[str, None] = '4e45f0a0551c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False, comment='id заказа'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='id пользователя'),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='Список товаров'),
    sa.Column('total_price', sa.Float(), nullable=False, comment='Общая стоимость'),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'SHIPPED', 'CANCELED', name='orderstatus'), nullable=False, comment='Статус заказа'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Время создания'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
